spring.application.name=wiki
server.port=8881

test.hello=HELLO

#Connect to Mysql localhost
spring.datasource.url=jdbc:mysql://localhost:3306/wiki@localhost?useSSL=false&serverTimezone=UTC
spring.datasource.username=root  # Your MySQL username
spring.datasource.password=root  # Your MySQL password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
