GET http://localhost:8881/hello
Accept: application/json

###

POST http://localhost:8881/hello/post
Content-Type: application/x-www-form-urlencoded

name = Vincent!

###
GET http://localhost:8080/test/list